dataset:
  path: datasets/pdt
  # text:
  #   label_column_name: sentiment
  #   text_column_name: content
  # path: datasets/dataset/twitter_validation.csv

display:
  monitor: 
    name: spectrum_monitor
    resolution:
      - 1536
      - 960
    width: 35
    distance: 60
  gui:
    button:
      size:
        - 250
        - 100
      margin: 20
      color: lightgrey
      text:
        color: black
        size: 30
    fixation_dot: 
      size: 10
      color: white
    aoe:
      - 750
      - 750

output:
  folder: output

model:
  folder: runtime_models
  module: custom_yolo_model
  class: CustomYoloModel

instructions:
  intro:
    - "Welcome to the study!"
    - ""
    - "In this experiment, you will see a series of images or text samples."
    - "Please look at each stimulus carefully, then select the appropriate option using the buttons below."
    - ""
    - "Press SPACE to begin."
  outro:
    - "Thank you for participating in this study!"
    - ""
    - "Your responses and recordings have been saved."
    - "You may now close the window or press ESC to exit."